- feedingwebapp/.env
- feedingwebapp/src/App.jsx
Remove the unnecessary env variable to hardcode the URL.
Tested during the 11-16 demo.
> Have rosbridge set domain name based on URL instead of hard-coded

- feeding_web_app_ros2_test/feeding_web_app_ros2_test/DummyRealSense.py
- feeding_web_app_ros2_test/feeding_web_app_ros2_test/FaceDetection.py
- feeding_web_app_ros2_test/feeding_web_app_ros2_test/SegmentFromPoint.py
- feeding_web_app_ros2_test/launch/feeding_web_app_dummy_nodes_launch.xml
- feedingwebapp/src/App.jsx
- feedingwebapp/src/Pages/Constants.js
- feedingwebapp/src/Pages/Header/Header.jsx
- feedingwebapp/src/Pages/Header/LiveVideoModal.jsx
- feedingwebapp/src/Pages/Home/Home.jsx
- feedingwebapp/src/Pages/Home/MealStates/BiteSelection.jsx
- feedingwebapp/src/Pages/Home/MealStates/DetectingFace.jsx
- feedingwebapp/src/Pages/Home/MealStates/PlateLocator.jsx
- feedingwebapp/src/Pages/Home/VideoFeed.jsx
- feedingwebapp/src/buttons/MaskButton.jsx
1. The web app often doesn't show a camera feed when returning to Bite Selection, if your phone falls asleep during Bite Selection, or if you put your phone on sleep (e.g., press the power button) during Bite Selection.
1. Further, sometimes even if it does render an image, it is a very old image (e.g., there is lots of latency).
2. Bite Selection overlays the mask on top of the **live video feed** for every mask (3 currently), hence maintaining 4 independent live video streams at once.
1. This post provides [an overview of 5 ways to stream videos for robots](https://transitiverobotics.com/blog/streaming-video-from-robots), and the pros/cons of each.
1. As documented in that post, latency/lag is a well-known issue with `web_video_server` because it guarantees delivery of every packet. The …
> Revamp In-App Video Streaming

- feedingwebapp/src/Pages/Home/MealStates/DetectingFace.jsx
Currently, once the robot/app gets to the staging configuration (`R_DetectingFace` in the app), the user *must* continue to their mouth. However, there are multiple cases where they won't want to, e.g.,
1. From the resting configuration, the user wanted to go back above the plate but clicked the wrong button.
2. `MoveToMouth` returns failure, but it is actually at the user's mouth. At this point, the user must click "Back" to go back, but then the "DetectingFace" screen needs to allow them to go back.
This PR adds two additional buttons to the `R_DetectingFace` page, to move to the resting configuration and to move back to the above plate configuration.
The above image shows the screen before this PR.
The above image shows the screen after this PR.
***
- …
> Allow users to move back from staging configuration

- feeding_web_app_ros2_test/launch/feeding_web_app_dummy_nodes_launch.xml
- feedingwebapp/src/Pages/Constants.js
- feedingwebapp/src/Pages/Home/MealStates/DetectingFace.jsx
- feedingwebapp/src/Pages/Home/VideoFeed.jsx
Joint PR with [`ada_feeding`#151](https://github.com/personalrobotics/ada_feeding/pull/151)
Although #106 improved video streaming by replacing the dependency on `web_video_server` with direct subscription to compressed images, the latency of this approach depends on the device. On a desktop computer, the video stream has 1-3 sec latency, but on an iPhone 11, it has increasing latency that gets into the tens of seconds.
Looking into it, the most likely reason for this is that [`roslibjs` uses EventEmitter2's `emit` event](https://github.com/personalrobotics/roslibjs/blob/af51b1550d4cc5241e19010ff2c4f980610f64b3/src/core/Topic.js#L79), which is synchronous. Thus, even if the subscriber on the ROS side has no queue, a queue builds up on the web app side.
The best solution to this, as …
> Temporary fix for video latency

- feedingwebapp/.env
- feedingwebapp/README.md
- feedingwebapp/package-lock.json
- feedingwebapp/package.json
- feedingwebapp/server.js
- feedingwebapp/src/App.jsx
- feedingwebapp/src/Pages/Constants.js
- feedingwebapp/src/Pages/Header/Header.jsx
- feedingwebapp/src/Pages/Header/LiveVideoModal.jsx
- feedingwebapp/src/Pages/Home/Home.jsx
- feedingwebapp/src/Pages/Home/MealStates/BiteSelection.jsx
- feedingwebapp/src/Pages/Home/MealStates/DetectingFace.jsx
- feedingwebapp/src/Pages/Home/MealStates/PlateLocator.jsx
- feedingwebapp/src/Pages/Home/VideoFeed.jsx
- feedingwebapp/src/robot/README.md
- feedingwebapp/src/robot/RobotVideoStreams.jsx
- feedingwebapp/src/robot/VideoStream.jsx
- feedingwebapp/src/webrtc/webrtc_helpers.js
- feedingwebapp/start_robot_browser.js
Joint with [`ada_feeding`#154](https://github.com/personalrobotics/ada_feeding/pull/154).
In service of #112 , this PR implements a WebRTC connection for streaming video from the robot to the client. It implements "Option A" from #112 . Specifically, it launches a headless browser on `lovelace` to be one end of the P2P connection. Although this should not be necessary (see Option B in #112 ), it was the most straightforward to implement given that is the approach [`stretch_teleop_interface`](https://github.com/hcrlab/stretch_teleop_interface/tree/master) used.
As such, this PR changes the web app's launch procedure on `lovelace`. Whereas earlier one had to launch the web app and the web_video_server, now they have to run:
1. The web app: `npm run start` (or `cd build; python3 -m …
> Implement WebRTC

- feedingwebapp/src/robot/RobotVideoStreams.jsx
- feedingwebapp/src/robot/VideoStream.jsx
- feedingwebapp/src/webrtc/webrtc_helpers.js
- feedingwebapp/start_robot_browser.js
This PR makes the following small changes to the WebRTC implementation in #112 :
1. Make the robot browser headless. (Hopefully, this will remove the need for the fake screen before launching the robot browser documented in the wiki).
2. Add comments to functions without it
> Small Fixes to WebRTC

- feedingwebapp/.env
- feedingwebapp/README.md
- feedingwebapp/package-lock.json
- feedingwebapp/package.json
- feedingwebapp/start_robot_browser.js
Although in development we serve the web app on port `3000` (to allow people with non-sudo access to run it), in production we serve it on port 80. Before this PR, that required changing the `.env` file.
After this PR, that involves just passing a command line argument to `start_robot_browser.js`, which aligns with how we specify to run it on port 80 in the first place.
I've updated the [wiki instructions](https://github.com/personalrobotics/pr_docs/wiki/ADA#commands-to-setup) accordingly.
> Allow `start_robot_browser.js` to take a command line port

- feedingwebapp/package-lock.json
- feedingwebapp/package.json
- feedingwebapp/src/Pages/Constants.js
- feedingwebapp/src/Pages/Footer/Footer.jsx
- feedingwebapp/src/Pages/GlobalState.jsx
- feedingwebapp/src/Pages/Header/Header.jsx
- feedingwebapp/src/Pages/Home/Home.jsx
- feedingwebapp/src/Pages/Home/MealStates/BiteDone.jsx
- feedingwebapp/src/Pages/Home/MealStates/CircleProgressBar.jsx
- feedingwebapp/src/Pages/Home/MealStates/DetectingFace.jsx
- feedingwebapp/src/Pages/Home/MealStates/DetectingFaceSubcomponent.jsx
- feedingwebapp/src/Pages/Home/MealStates/RobotMotion.jsx
- feedingwebapp/src/Pages/Home/VideoFeed.jsx
- feedingwebapp/src/Pages/Settings/BiteTransfer.jsx
- feedingwebapp/src/Pages/Settings/Main.jsx
- feedingwebapp/src/Pages/Settings/Settings.jsx
- feedingwebapp/src/ros/ros_helpers.js
- feedingwebapp/src/webrtc/webrtc_helpers.js
Joint with [`ada_feeding`#155](https://github.com/personalrobotics/ada_feeding/pull/155).
Different users have different neck mobilities, and thus it is crucial for them to be able to customize how close the robot gets to their mouth during bite transfer. This PR accomplishes that through the following changes:
1. Re-implementing the settings menu, and removing all un-implemented settings.
3. Generalizing RobotMotion and DetectingFace to be able to be called from within the settings menu, without impacting non-settings global state.
4. Have the settings menu retrieve the current parameter from the robot (i.e., parameters are stored on the robot, not in web app cookies).
5. Allow the user to change the distance to mouth and try it out.
6. When the `Done` button is clicked, it executes …
> Allow users to customize the distance to mouth during bite transfer

- feedingwebapp/server.js
- feedingwebapp/src/Pages/GlobalState.jsx
- feedingwebapp/src/Pages/Home/MealStates/DetectingFace.jsx
This PR overrides auto-continue if the robot arrived at `DetectingFace` through the `MoveFromMouth` state. This is to avoid the case where the user mistakenly presses back, and then it automatically moves to their mouth.
This PR also adds better error handling to the WebRTC server.
***
> Override AutoContinue if moving back from mouth

- feedingwebapp/package-lock.json
- feedingwebapp/package.json
- feedingwebapp/src/Pages/Constants.js
- feedingwebapp/src/Pages/GlobalState.jsx
- feedingwebapp/src/Pages/Home/MealStates/BiteAcquisitionCheck.jsx
- feedingwebapp/src/Pages/Home/MealStates/RobotMotion.jsx
After any robot motion, the last reported action response is cached as part of the GlobalState.
After Bite Acquisition, this response is used to construct a call to AcquisitionReport, which updates the robot's online learning policy based on success or failure of the action.
Additionally, added a toast to the screen upon selecting whether to re-aquire or not.
Tested on real with the `ros2-devel` branch of https://github.com/personalrobotics/ada_feeding
No python code changes: black not run
No change to user flow, so that box is not checked.
***
> Call AcquisitionReport service after food-on-fork question

- feedingwebapp/package-lock.json
- feedingwebapp/package.json
- feedingwebapp/server.js
- feedingwebapp/src/Pages/GlobalState.jsx
- feedingwebapp/src/Pages/Home/MealStates/BiteSelection.jsx
- feedingwebapp/src/Pages/Home/MealStates/DetectingFace.jsx
- feedingwebapp/src/Pages/Home/MealStates/DetectingFaceSubcomponent.jsx
- feedingwebapp/src/Pages/Home/VideoFeed.jsx
- feedingwebapp/src/robot/VideoStream.jsx
Depending on the table height, the plate might only take up a small fraction of the robot's camera feed during bite selection. This makes it hard for the user to select a food item on the plate. This PR enables the user to zoom into the plate
Sim:
- Note: this display is not the best, but is fine.
Real:
***
> Allow Users to Zoom Into Bite Selection Video

- feedingwebapp/README.md
- feedingwebapp/package-lock.json
- feedingwebapp/package.json
- feedingwebapp/server.js
- feedingwebapp/src/Pages/GlobalState.jsx
- feedingwebapp/src/Pages/Home/MealStates/DetectingFace.jsx
- feedingwebapp/src/buttons/MaskButton.jsx
- feedingwebapp/src/webrtc/webrtc_helpers.js
- feedingwebapp/start_robot_browser.js
1. Add better logging.
2. Make Auto-Continue the default for DetectingFace
3. Allow for changing number of MaskButtons between renders (e.g., because if the masks are too close to the edge of the screen, SegmentFromPoint might return fewer than 3 masks)
Tested over the course of the 1/22-1/24 user studies.
***
- [N/A] Thoroughly test your code's functionality, including unintended uses.
- [N/A] Fully test the responsiveness of the feature as documented in the [Responsiveness Testing Guidelines](https://github.com/personalrobotics/feeding_web_interface/blob/main/feedingwebapp/ResponsivenessTesting.md). If you deviate from those guidelines, document above why you …
> Consolidated infra changes from RSS Demo

- README.md
- feeding_web_app_ros2_test/README.md
- feeding_web_app_ros2_test/feeding_web_app_ros2_test/MoveFromMouth.py
- feeding_web_app_ros2_test/launch/feeding_web_app_dummy_nodes_launch.xml
- feeding_web_app_ros2_test/setup.py
- feedingwebapp/README.md
1. Add `MoveFromMouth` dummy action.
2. For all setup, point to [the top-level `ada_feeding` README](https://github.com/personalrobotics/ada_feeding/blob/ros2-devel/README.md).
> Centralize dependencies using `rosdep`

- feeding_web_app_ros2_test/feeding_web_app_ros2_test/FaceDetection.py
- feeding_web_app_ros2_test/feeding_web_app_ros2_test/FoodOnForkDetection.py
- feeding_web_app_ros2_test/launch/feeding_web_app_dummy_nodes_launch.xml
- feeding_web_app_ros2_test/setup.py
- feedingwebapp/src/Pages/Constants.js
- feedingwebapp/src/Pages/GlobalState.jsx
- feedingwebapp/src/Pages/Home/MealStates/BiteAcquisitionCheck.jsx
- feedingwebapp/src/Pages/Home/MealStates/BiteDone.jsx
Joint with [`ada_feeding`#169](https://github.com/personalrobotics/ada_feeding/pull/169), this PR adds the web app capability to auto-continue once food has consistently been (not( detected on the fork for 3 seconds, both in BiteDone and BiteAcquisitionCheck, and auto-continue if so. The user has the option to decide whether to enable or disable this auto-continue. The 5 secs and probability threshold are currently hardcoded; customizing them from the settings menu will be another PR.
**Test with dummy nodes**:
**Test on the real robot**:
***
> Added FoodOnFork Detection to Web App

- feeding_web_app_ros2_test/feeding_web_app_ros2_test/FaceDetection.py
- feedingwebapp/src/Pages/Constants.js
- feedingwebapp/src/Pages/GlobalState.jsx
- feedingwebapp/src/Pages/Settings/BiteTransfer.jsx
- feedingwebapp/src/Pages/Settings/Main.jsx
This PR, paired with [`ada_feeding`#172](https://github.com/personalrobotics/ada_feeding/pull/172), allows users to maintain multiple parameter configurations and switch between them.
- On the main settings page, the user can choose which preset they want to use. If they want to change any parameters, they must be on a non-default preset.
- On any page that allows changing settings (e.g., the BiteTransfer page), the user can change settings for that preset, and can revert settings for that preset to any of the other presets.
Pull this code and [`ada_feeding`#172](https://github.com/personalrobotics/ada_feeding/pull/172) code and rebuild.
***
> Allow users to set multiple parameter presets

- feeding_web_app_ros2_test/feeding_web_app_ros2_test/DummyRealSense.py
- feeding_web_app_ros2_test/launch/feeding_web_app_dummy_nodes_launch.xml
- feedingwebapp/src/Pages/Home/MealStates/BiteAcquisitionCheck.jsx
This PR, joint with [ada_feeding#174](https://github.com/personalrobotics/ada_feeding/pull/174), extends the dummy RealSense code to also publish the compressed depth image.
This PR also makes a small change to how food-on-fork is handled after bite acquisition; if too few points are detected (status -1, as defined in [the message](https://github.com/personalrobotics/ada_feeding/blob/c6f9674fee737067fdbbcd594774098202078338/ada_feeding_msgs/msg/FoodOnForkDetection.msg#L9)), assume there is no FoF.
***
- [N/A] Format React code with `npm run format`
- [N/A] Thoroughly test your code's functionality, including unintended uses.
- [N/A] Fully test the responsiveness of the feature as documented in the [Responsiveness Testing …
> Switch to Compressed Depth Images

- feedingwebapp/src/Pages/GlobalState.jsx
- feedingwebapp/src/Pages/Header/TeleopSubcomponent.jsx
- feedingwebapp/src/Pages/Settings/CustomizeConfiguration.jsx
- feedingwebapp/src/Pages/Settings/Main.jsx
- feedingwebapp/src/Pages/Settings/Settings.jsx
Building off of #133 , this PR allows users to customize the resting configuration. This essentially involves a small generalization of the AbovePlate component.
User-driven customization poses a problem for the collision scene. For example, in this case, if they customize the elbow of the robot to be below the `in_front_of_wheelchair_wall`, then plans from the resting configuration will likely not succeed. With any customization, if the user moves the arm in collision with the workspace wall, all plans will fail. We need to think further about how to modify the collision scene as a function of these customizations, either automatically or allowing users to do it.
***
- [N/A] Format Python code by running `python3 -m black .` in the top-level of this …
> Allow users to customize the resting configuration

- feedingwebapp/src/Pages/Constants.js
- feedingwebapp/src/Pages/Settings/CustomizeConfiguration.jsx
- feedingwebapp/src/Pages/Settings/SettingsPageParent.jsx
- feedingwebapp/src/ros/ros_helpers.js
As of [`ada_feeding`#181](https://github.com/personalrobotics/ada_feeding/pull/181), the robot code exposes an action to recompute workspace walls based on the currently-used robot arm configurations. This PR modifies the web app to call that action every time a configuration parameter is saved. This enables users to customize configurations without worrying about it leading the robot to be in collision with the workspace walls.
- The main issues with customizing all the configurations to get "short" robot arm motions was: (a) wrench thresholds exceeded, particularly if we did a full rotation of the arm; and (b) rosbridge / ros2 not reliably sending messages. Nothing dangerous happened as a result of this, but it sometimes slowed progress and it was unclear what to do.
- Currently, the …
> Reset Workspace Walls When Customizing Configurations

- feedingwebapp/src/Pages/Constants.js
- feedingwebapp/src/Pages/Header/InfoModal.jsx
- feedingwebapp/src/Pages/Header/TeleopSubcomponent.jsx
- feedingwebapp/src/ros/ros_helpers.js
This PR, which builds upon [`ada_feeding`#183](https://github.com/personalrobotics/ada_feeding/pull/183), extends the `TeleopSubcomponent` as follows:
1. On mount and when the refresh button is clicked, has the teleop button re-tare the F/T sensor.
2. From the `InfoModal`, gives users the option to increase the F/T threshold (to 75N) and restore it (back to 1N).
***
> Allow `TeleopSubcomponent` to re-tare and change F/T threshold

- feedingwebapp/src/Pages/Constants.js
- feedingwebapp/src/Pages/GlobalState.jsx
- feedingwebapp/src/Pages/Settings/Main.jsx
- feedingwebapp/src/Pages/Settings/Settings.jsx
This PR builds off of recent PRs (#136 , #135 , etc.) to allow users to customize the stow configuration.
***
> Allow users to customize the stow configuration

- feedingwebapp/src/Pages/Constants.js
- feedingwebapp/src/Pages/Home/Home.jsx
- feedingwebapp/src/Pages/Home/MealStates/RobotMotion.jsx
Sometimes, even though acquisition succeeds, the robot thinks it encountered an error. This PR shows the user the option to proceed to the resting position even if it gets an error, to account for that scenario.
***
> Allow users to skip acquisition on error

- feedingwebapp/public/robot_state_imgs/forward.svg
- feedingwebapp/src/Pages/Constants.js
- feedingwebapp/src/Pages/GlobalState.jsx
- feedingwebapp/src/Pages/Settings/AutoContinue.jsx
- feedingwebapp/src/Pages/Settings/Main.jsx
- feedingwebapp/src/Pages/Settings/Settings.jsx
- feedingwebapp/src/Pages/Settings/SettingsPageParent.jsx
This PR adds another element to the settings menu that allows users to toggle auto-continue options. Although auto-continue options nominally can be toggled from the app, the issue is that once they are checked, the robot could potentially move past that screen very fast, so the user may not have time to un-toggle the auto-continue settings. This PR addresses that, by giving users another location (in the settings menu) to toggle auto-continue settings.
***
> Allow users to change auto-continue from Settings Menu

- feedingwebapp/src/Pages/GlobalState.jsx
- feedingwebapp/src/Pages/Home/Home.jsx
- feedingwebapp/src/Pages/Home/MealStates/BiteAcquisitionCheck.jsx
- feedingwebapp/src/Pages/Home/MealStates/RobotMotion.jsx
- feedingwebapp/src/Pages/Settings/BiteTransfer.jsx
- feedingwebapp/src/ros/ros_helpers.js
This PR allows a successful acquisition report even when the user clicks "Skip Acquisition" if acquisition failed (i.e., it failed after acquiring the food). The PR also makes "Skip Acquisition" go directly to the staging configuration.
Note: [`ada_feeding`#197](https://github.com/personalrobotics/ada_feeding/pull/197) should be merged before this!
***
> Improve Acquisition Report

- feedingwebapp/src/Pages/Header/InfoModal.jsx
This PR, Motivated by the 2024 deployment, creates the option to show the video feed in the Teleop modal. In practice, this works fine when the user is accessing the modal on their computer, but not great on a screen as smart as the smartphone. Thus, by default, we disable this.
***
> Create option to show Video Feed in Teleop Modal
